spring:
  data:
    mongodb:
      host: main.junnyland.com
      port: 27017
      password: junny1234
      username: junnyland
      auto-index-creation: true
      authentication-database: admin
      database: junutv
  main:
    web-application-type: reactive

jwt:
  token:
    private: classpath:app.key
    public: classpath:app.pub
    time: 1800000